#! /usr/bin/ruby

require 'rubygems'
require 'rack'
require "xml"
require 'connect.rb'

class HelloWorld
        def call(env)
                req = Rack::Request.new(env)
                #name = req.GET['name']
                #html=req.body.read

                c=req.query_string()

                if(c=="die")
                        abort
                end
                
                sql="select * from geopoints";

st=$dbh.prepare(sql);

st.execute();
xml = '<gts query="message/load[#{inputstring}]">';

while row = st.fetch do
xml += '<content lat="#{row[1]}" lon="#{row[2]}" user="#{row[5]}" id="#{row[0]}" timestamp="#{row[4]}">'
     
     puts row[0],":",row[1],"<br>"

end

                xml = "<gts query='message/load[bbox=12,43,23,12]'>
                        <content lat='48.2' lon='15.6' user='franzi' id='234' timestamp='2010-10-03T20:35:37'>
                            Wir moegen euch nicht
                        </content>
                        <content lat='49.3' lon='-13.6' user='elfriede' id='134' timestamp='2010-10-07T22:15:27'>
                            Elfriede is at home.
                        </content>
                      </gts>"
                [200, {"Content-Type" => "text/xml"}, [xml]]

         end

end

# Deploy using WEBrick handler
Rack::Handler::FastCGI.run HelloWorld.new
