#! /usr/bin/ruby

require 'rubygems'
require 'rack'
require 'xml'
require '../functions/connect.rb'

$dbh=dbconnect

class MessageLoad
	def call(env)
		req = Rack::Request.new(env)
		
		$dbh.ping()

		c=req.query_string();
		if(!c)
			c="";
		end

		if(c=="die")
		    abort
		elsif c=="bbox"
			#das ist kaputt
		    #   bboxarray = c.split(/([(0-9)(\.?(0-9)*)?],?[(0-9)(\.?(0-9)*)?]*)/)

		    #puts YAML::dump(c)
		    #puts "query: ",c
		end #End if
		cc=c.split("=")[1]
		#cc="-180,-90,180,90";
		bboxarray = cc.split(",")
		s=bboxarray[0]
		w=bboxarray[1]
		e=bboxarray[2]
		n=bboxarray[3]




		begin
			sql="SELECT id,X(wgs),Y(wgs),message,time_stamp  FROM `geopoints` WHERE (MBRContains( GeomFromText( ? ),`wgs`))   ORDER BY time_stamp DESC LIMIT 10"

			st=$dbh.prepare(sql);


			poly=s.to_s+" "+w.to_s+","+n.to_s+" "+w.to_s+","+n.to_s+" "+e.to_s+","+s.to_s+" "+ e.to_s+","+s.to_s+" "+w.to_s
			polygon="POLYGON(("+poly+"))"
			st.execute(polygon);

			xml = "<gts  query='message/load[#{c}]' poly='#{poly}'>";

			while row = st.fetch do
				xml += "<content lat='#{row[1]}' lon='#{row[2]}' user='' id='#{row[0]}' timestamp='#{row[4]}'>";
				xml =xml+ row[3];
				xml += "</content>";
			end


			xml =xml+ '</gts>';
			return  [200, {"Content-Type" => "text/xml"}, [xml]]

		rescue Exception => e
			xml = "<error no='6'>DB Error: #{e.message}.</error>"
			return[500,{"Content-Type" => "text/xml"},[xml]]
			
		end

	end
end

Rack::Handler::FastCGI.run MessageLoad.new
