#! /usr/bin/ruby

require 'rubygems'
require 'connect.rb'
require 'xml'
require 'rack'
require 'key.rb'

class UserLogin
    def call(env)

    req= Rack::Request.new(env)
    
    doc = XML::Document.string(req.body.read);
    
    doc.find("/gts/username") {|node| 
    username = node.content;
    };
    
    doc.find("/gts/password") {|node| 
    password = node.content;
    };
    #at request check if user is logged in
    #login or update
    end
    def login(username, key)
        dbh = dbconnect

        sql = "insert into geologgedin (username,KEY) values (?,?);"
        begin
            st = dbh.prepare(sql)
            st.execute(username, key)
            
           xml = "<gts query='user/login'><success key='#{key}'/></gts>"
           return [200,{"Content-Type" => "text/xml"},[xml]]  
 
       rescue Exception => e
           xml = "<error no='6'>DB Error: #{e.message}.</error>"
           return [200,{"Content-Type" => "text/xml"},[xml]]  
        end
    end
end
