#! /usr/bin/ruby

require 'rubygems'
require 'connect.rb'
require 'xml'
require 'rack'
require 'digest/sha1'

class UserRegister
    def call(env)
    
    req = Rack::Request.new(env)
    doc = XML::Document.string(req.body.read)

#Errorhandling

#read the file
    begin
        relaxng_doc = XML::Document.file('../../interface/user/register/request.rng')
        relaxng_sch = XML::RelaxNG.document(relaxng_doc)
    rescue
        xml = "<error no='5'>Couldn't open relaxng file. Check permissions or path</error>"
        [200,{"Content-Type" => "text/xml"},[xml]]
    end
#validate relax ng    
    begin 
        doc.validate_relaxng(relaxng_sch)
    rescue Exception => e
         xml = "<error no='7'>XML ERROR: #{e.message}</error>"
        [200,{"Content-Type" => "text/xml"},[xml]]
    end
=begin
c=req.query_string()
if(c=="die")
abort
end
=end

    userxml = doc.find("/gts/username")
    passxml = doc.find("/gts/password")

    username = userxml.first.content
    password = Digest::SHA1.hexdigest(passxml.first.content)

        if (create(username,password))
            xml = "<gts query='user/register'><success key='EEE33343AAEF'/></gts>"
            [200,{"Content-Type" => "text/xml"},[xml]]  
        else
            xml = "<error no='6'>you fail</error>"
            [200,{"Content-Type" => "text/xml"},[xml]]  
        end
    end
    def create(username,password)
        $dbh = dbconnect

        sql = "insert into geousers (username,password) values (?,?);"
        st = $dbh.prepare(sql)
        return st.execute(username,password)
    end
end

Rack::Handler::FastCGI.run UserRegister.new
