#! /usr/bin/ruby

require 'rubygems'
require 'connect.rb'
require 'xml'
require 'rack'

class UserRegister
    def call(env)
    
    req = Rack::Request.new(env)
    doc = XML::Document.string(req.body.read)

#Errorhandling
    begin
        relaxng_doc = XML::Document.file('../../interface/user/register/request.rng')
    rescue
        xml = "<error no='5'>Couldn't open relaxng file. Check permissions or path</error>"
        [200,{"Content-Type" => "text/xml"},[xml]]        
    end

    relaxng_sch = XML::RelaxNG.document(relaxng_doc)

    username = doc.find("/gts/username")
    password = doc.find("/gts/password")

    username.first.content
    password.first.content

    create(username,password)
    end
    def create(username,password)
        $dbh = dbconnect

        sql = "insert into geousers (username,password) values (?,?,?);"
        st = $dbh.prepare(sql)
        st.execute(username,password)
    end
end

Rack::Handler::FastCGI.run UserRegister.new
