#! /usr/bin/ruby

require 'rubygems'
require '../functions/connect.rb'
require 'xml'
require 'rack'
require 'digest/sha1'

$dbh=dbconnect

XML::Error.set_handler(&XML::Error::QUIET_HANDLER)

class UserSetAvatar

    def call(env)
        
        req= Rack::Request.new(env);
	
        #kill the server from outside
		c=req.query_string()
		if(c=="die")
            puts "FAAAAAAAAAAAATHER"
    		abort
		end

		#Errorhandling
        #read the xml file    
		begin
			doc = XML::Document.string(req.body.read);			
		rescue Exception => e
			xml = "<error no='1'>XML ERROR while calling  user/setavatar: #{e.message}</error>"
			return [501,{"Content-Type" => "text/xml"},[xml]] 
		end
		#done reading xml file

		#read the rng file
		begin
			relaxng_doc = XML::Document.file('../../interface/user/setavatar/request.rng')
			relaxng_sch = XML::RelaxNG.document(relaxng_doc)
			#validate relax ng    
				begin 
					doc.validate_relaxng(relaxng_sch)
				rescue Exception => e
					xml = "<error no='7'>XML ERROR: #{e.message}</error>"
					return [501,{"Content-Type" => "text/xml"},[xml]]                
				end
            #done validating
		rescue
			xml = "<error no='5'>Couldn't open relaxng file. Check permissions or path</error>"
			return [501,{"Content-Type" => "text/xml"},[xml]]
		end
        #done reading rng file
      
        key=doc.root.attributes.get_attribute("key").value;
 
        #check if user is logged in
        sql_getuser = "select username from geologgedin where logginschlussel =?;"
            
        st_getuser=$dbh.prepare(sql_getuser)
        st_getuser.execute(key)
        username = "" 
        
        if $dbh.affected_rows > 0
        #user ist eingelogt
           while row = st_getuser.fetch do
                username = row[0]
                break
            end
               
                st_update = $dbh.prepare("UPDATE geousers SET avatar=? where username=?")
                avatarurl = doc.find("/gts/url").first.content
                st_update.execute(avatarurl,username)
                 
                xmlresponse = "<gts query='user/setavatar'>"
                xmlresponse = xmlresponse+"<success />"
                xmlresponse = xmlresponse+"</gts>"
               return [200,{"Content-Type" => "text/xml"},[xmlresponse]]           
                       
        else
        #user ist nicht eingelogt -> error   
          xml = "<error no='666'>U r not loged in</error>"
          return [501,{"Content-Type" => "text/xml"},[xml]]
          
        end
        #user login check ende
       
    end #end call

end #end UserSetAvatar

Rack::Handler::FastCGI.run UserSetAvatar.new
